// Bundles the three.js game into a single self-contained HTML page.
//
//   node game/build.mjs          one-off build
//   node game/build.mjs --watch  rebuild on change
//
// Outputs:
//   game/dist/index.html          open in a browser to play on desktop
//   src/generated/gameHtml.ts     the same page as a string, loaded by the app's WebView
import { context, build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const watch = process.argv.includes('--watch');

const FONTS = [
  ['Fredoka', 500, 'fredoka/500Medium/Fredoka_500Medium.ttf'],
  ['Fredoka', 600, 'fredoka/600SemiBold/Fredoka_600SemiBold.ttf'],
  ['Fredoka', 700, 'fredoka/700Bold/Fredoka_700Bold.ttf'],
  ['Orbitron', 700, 'orbitron/700Bold/Orbitron_700Bold.ttf'],
  ['Orbitron', 800, 'orbitron/800ExtraBold/Orbitron_800ExtraBold.ttf'],
];

function fontFaces() {
  return FONTS.map(([family, weight, file]) => {
    const data = readFileSync(join(root, 'node_modules/@expo-google-fonts', file)).toString('base64');
    return `@font-face{font-family:'${family}';font-weight:${weight};font-style:normal;font-display:block;src:url(data:font/ttf;base64,${data}) format('truetype')}`;
  }).join('\n');
}

function page(js) {
  const css = readFileSync(join(here, 'src/ui/style.css'), 'utf8');
  const safeJs = js.replace(/<\/script/gi, '<\\/script');
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<meta name="theme-color" content="#03040a">
<title>Hull Breach: Leviathan</title>
<style>
${fontFaces()}
${css}
</style>
</head>
<body>
<canvas id="game"></canvas>
<div id="vignette"></div>
<div id="touch"></div>
<div id="ui"></div>
<script>
${safeJs}
</script>
</body>
</html>
`;
}

function emit(js) {
  const html = page(js);
  mkdirSync(join(here, 'dist'), { recursive: true });
  writeFileSync(join(here, 'dist/index.html'), html);
  mkdirSync(join(root, 'src/generated'), { recursive: true });
  writeFileSync(
    join(root, 'src/generated/gameHtml.ts'),
    `// Generated by game/build.mjs. Do not edit: run \`npm run game:build\`.\nconst html: string = ${JSON.stringify(html)};\nexport default html;\n`,
  );
  console.log(`game: wrote ${(html.length / 1024).toFixed(0)} KB`);
}

const options = {
  entryPoints: [join(here, 'src/main.ts')],
  bundle: true,
  format: 'iife',
  target: ['es2020', 'chrome90', 'safari15'],
  minify: !watch,
  sourcemap: false,
  write: false,
  legalComments: 'none',
  logLevel: 'warning',
  define: { 'process.env.NODE_ENV': '"production"' },
  plugins: [
    {
      name: 'emit-html',
      setup(b) {
        b.onEnd((result) => {
          if (result.errors.length || !result.outputFiles?.length) return;
          emit(result.outputFiles[0].text);
        });
      },
    },
  ],
};

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log('game: watching for changes...');
} else {
  await build(options);
}
