import type { ThemeId } from './levelTypes';

export type ParticleMood = 'snow' | 'spores' | 'embers' | 'petals' | 'sparks' | 'motes' | 'pollen' | 'dust' | 'snowfall' | 'leaves' | 'ash';

/** How the ground of an outdoor region is painted. */
export type GroundStyle = 'grass' | 'sand' | 'snow' | 'rock' | 'jungle' | 'basalt';

/** The open-air look of a Gaia Nova region: natural ground and cliffs, a sun, clouds and a horizon. */
export interface Outdoor {
  ground: GroundStyle;
  /** A second ground colour for patches and detail. */
  ground2: string;
  /** Cliff faces: the rock and its darker strata. */
  rock: string;
  rockDark: string;
  /** The valley floor far below the play area (a lava lake glows). */
  below: string;
  belowGlow?: boolean;
  /** Colour of the sun's disc in the sky. */
  sunDisc: string;
  /** Cloud colour, or null for a clear sky. */
  clouds: string | null;
  /** Far mountains or dunes on the horizon. */
  hills: string;
  /** Stars in the sky (a twilight region). */
  stars: boolean;
  /**
   * Sky-islands: far below there is no valley, just a soft sea of clouds (with a few more islands
   * floating in it), and the far mountains become distant cloud banks.
   */
  cloudSea?: boolean;
  /** A reef in the open sea: far below is the deep blue seabed, and the horizon stays low and flat. */
  sea?: boolean;
}

export interface Theme {
  skyTop: string;
  skyBottom: string;
  fog: string;
  fogNear: number;
  fogFar: number;
  floor: string;
  floorLine: string;
  floorSide: string;
  ice: string;
  wall: string;
  /** Colour of the wall light strips and trims. */
  wallTrim: string;
  edge: string;
  hazard: string;
  hazardDeep: string;
  hemiSky: string;
  hemiGround: string;
  hemi: number;
  sun: string;
  sunI: number;
  accent: string;
  mood: ParticleMood;
  /** Open to space (stars below the walkways) instead of deep machinery shafts. */
  space: boolean;
  /** Bloom strength for this deck's light strips and glowing hazards. */
  bloom: number;
  /** Set for the outdoor regions of Gaia Nova; ship decks leave it out. */
  outdoor?: Outdoor;
}

export const THEMES: Record<ThemeId, Theme> = {
  cryo: {
    skyTop: '#02060e',
    skyBottom: '#0a1c30',
    fog: '#061222',
    fogNear: 44,
    fogFar: 145,
    floor: '#6b7784',
    floorLine: '#3c4652',
    floorSide: '#2a323c',
    ice: '#6a8a9e',
    wall: '#4b5968',
    wallTrim: '#6fe3ff',
    edge: '#6fe3ff',
    hazard: '#55eaff',
    hazardDeep: '#06384a',
    hemiSky: '#bfe4ff',
    hemiGround: '#0e1a28',
    hemi: 0.55,
    sun: '#eaf6ff',
    sunI: 1.55,
    accent: '#6fe3ff',
    mood: 'snow',
    space: false,
    bloom: 0.25,
  },
  hydro: {
    skyTop: '#030805',
    skyBottom: '#10220f',
    fog: '#0a160b',
    fogNear: 42,
    fogFar: 140,
    floor: '#61675a',
    floorLine: '#3b4232',
    floorSide: '#2b2a22',
    ice: '#bfe0a8',
    wall: '#46503f',
    wallTrim: '#b8ff5a',
    edge: '#c8ff5a',
    hazard: '#8cff2a',
    hazardDeep: '#1c4208',
    hemiSky: '#f4f0c8',
    hemiGround: '#121c0c',
    hemi: 0.7,
    sun: '#fff2d6',
    sunI: 1.55,
    accent: '#b8ff5a',
    mood: 'spores',
    space: false,
    bloom: 0.23,
  },
  engine: {
    skyTop: '#060201',
    skyBottom: '#2a0c03',
    fog: '#160804',
    fogNear: 42,
    fogFar: 138,
    floor: '#5f5853',
    floorLine: '#3a322c',
    floorSide: '#2a221e',
    ice: '#c9b8a8',
    wall: '#4e443e',
    wallTrim: '#ffa23a',
    edge: '#ffb13a',
    hazard: '#ff6a12',
    hazardDeep: '#5a1400',
    hemiSky: '#ffd6ae',
    hemiGround: '#1e0e06',
    hemi: 0.65,
    sun: '#ffe0c0',
    sunI: 1.5,
    accent: '#ffa23a',
    mood: 'embers',
    space: false,
    bloom: 0.25,
  },
  habitat: {
    skyTop: '#05030c',
    skyBottom: '#1e1034',
    fog: '#110a1f',
    fogNear: 46,
    fogFar: 155,
    floor: '#6b6676',
    floorLine: '#443e52',
    floorSide: '#2c2638',
    ice: '#d8d0ff',
    wall: '#4f4861',
    wallTrim: '#ff7fd0',
    edge: '#ffc85a',
    hazard: '#c05cff',
    hazardDeep: '#34105a',
    hemiSky: '#ffe0f4',
    hemiGround: '#1a1228',
    hemi: 0.75,
    sun: '#fff0f8',
    sunI: 1.5,
    accent: '#ff7fd0',
    mood: 'petals',
    space: true,
    bloom: 0.23,
  },
  security: {
    skyTop: '#050203',
    skyBottom: '#200a0e',
    fog: '#12070a',
    fogNear: 42,
    fogFar: 138,
    floor: '#60646c',
    floorLine: '#3a3d44',
    floorSide: '#26292f',
    ice: '#c8ccd6',
    wall: '#454a54',
    wallTrim: '#ff3a4c',
    edge: '#ff5a66',
    hazard: '#5ec0ff',
    hazardDeep: '#0c2c52',
    hemiSky: '#ffe2e2',
    hemiGround: '#150c0e',
    hemi: 0.65,
    sun: '#ffffff',
    sunI: 1.55,
    accent: '#ff3a4c',
    mood: 'sparks',
    space: false,
    bloom: 0.27,
  },
  bridge: {
    skyTop: '#02030a',
    skyBottom: '#171040',
    fog: '#0a0820',
    fogNear: 48,
    fogFar: 160,
    floor: '#565d83',
    floorLine: '#343a64',
    floorSide: '#1e2348',
    ice: '#cfd6ff',
    wall: '#363e72',
    wallTrim: '#ff5fc8',
    edge: '#ff8ad8',
    hazard: '#ff4fbf',
    hazardDeep: '#4a0a3a',
    hemiSky: '#e4d8ff',
    hemiGround: '#120e2e',
    hemi: 0.75,
    sun: '#fff2ff',
    sunI: 1.55,
    accent: '#ff5fc8',
    mood: 'motes',
    space: true,
    bloom: 0.27,
  },
  plains: {
    skyTop: '#3f86d6',
    skyBottom: '#d6ecf6',
    fog: '#c4dcea',
    fogNear: 60,
    fogFar: 200,
    floor: '#5f9a3a',
    floorLine: '#3f6e24',
    floorSide: '#6b4a2e',
    ice: '#a8d8f0',
    wall: '#8a7f6e',
    wallTrim: '#e8d890',
    edge: '#c8e890',
    hazard: '#5ac8ff',
    hazardDeep: '#1a5a86',
    hemiSky: '#e2f2ff',
    hemiGround: '#4a5a2a',
    hemi: 1.0,
    sun: '#fff3d8',
    sunI: 2.1,
    accent: '#ffd166',
    mood: 'pollen',
    space: false,
    bloom: 0.12,
    outdoor: { ground: 'grass', ground2: '#86b84e', rock: '#8d8270', rockDark: '#5e5446', below: '#3f6e2c', sunDisc: '#fff6d0', clouds: '#ffffff', hills: '#6f90b0', stars: false },
  },
  desert: {
    skyTop: '#3b84cc',
    skyBottom: '#f4ddb0',
    fog: '#ecd6ae',
    fogNear: 60,
    fogFar: 205,
    floor: '#d9b67a',
    floorLine: '#b8935a',
    floorSide: '#a77a48',
    ice: '#c8e8f0',
    wall: '#c98a54',
    wallTrim: '#7fe6ff',
    edge: '#f0d8a0',
    hazard: '#ff9a3a',
    hazardDeep: '#3a1a08',
    hemiSky: '#fff2dc',
    hemiGround: '#8a6a40',
    hemi: 1.0,
    sun: '#fff0d0',
    sunI: 2.2,
    accent: '#7fe6ff',
    mood: 'dust',
    space: false,
    bloom: 0.14,
    outdoor: { ground: 'sand', ground2: '#e8c890', rock: '#c4844c', rockDark: '#8a5430', below: '#c8a06a', sunDisc: '#fffbe8', clouds: null, hills: '#c8946a', stars: false },
  },
  snow: {
    skyTop: '#1d2c5a',
    skyBottom: '#a8c8e8',
    fog: '#b4c8de',
    fogNear: 48,
    fogFar: 170,
    floor: '#e8f0f8',
    floorLine: '#b8c8d8',
    floorSide: '#7a8aa0',
    ice: '#8fcaec',
    wall: '#8e9cb0',
    wallTrim: '#7fe6ff',
    edge: '#e8f4ff',
    hazard: '#5ad8ff',
    hazardDeep: '#0a2a48',
    hemiSky: '#dfe8ff',
    hemiGround: '#5a6a88',
    hemi: 0.9,
    sun: '#ffe6d0',
    sunI: 1.7,
    accent: '#7fe6ff',
    mood: 'snowfall',
    space: false,
    bloom: 0.16,
    outdoor: { ground: 'snow', ground2: '#cfe0f0', rock: '#7c8aa0', rockDark: '#4c5870', below: '#d8e6f4', sunDisc: '#ffd8c0', clouds: '#e8eef8', hills: '#9aaecc', stars: true },
  },
  rockies: {
    skyTop: '#3874bc',
    skyBottom: '#dae6f0',
    fog: '#c6d4e0',
    fogNear: 58,
    fogFar: 200,
    floor: '#8a8a72',
    floorLine: '#6a6a58',
    floorSide: '#6a5a48',
    ice: '#b8e0f4',
    wall: '#8a7a68',
    wallTrim: '#ffb347',
    edge: '#d8d0b0',
    hazard: '#6ad0ff',
    hazardDeep: '#123a5a',
    hemiSky: '#e6f0ff',
    hemiGround: '#5a5040',
    hemi: 0.95,
    sun: '#fff4e0',
    sunI: 2.0,
    accent: '#ffb347',
    mood: 'pollen',
    space: false,
    bloom: 0.12,
    outdoor: { ground: 'rock', ground2: '#8f9a6a', rock: '#8c7c6a', rockDark: '#5a4c3e', below: '#5f7a4a', sunDisc: '#fff6d8', clouds: '#ffffff', hills: '#7a8aa8', stars: false },
  },
  jungle: {
    skyTop: '#2e6a5c',
    skyBottom: '#c4e4b4',
    fog: '#94bc9c',
    fogNear: 40,
    fogFar: 145,
    floor: '#4a7a2a',
    floorLine: '#2f5a1a',
    floorSide: '#4a3420',
    ice: '#a8e0d0',
    wall: '#5a6a48',
    wallTrim: '#ff6fcf',
    edge: '#a8e070',
    hazard: '#9dff3a',
    hazardDeep: '#1a3a0a',
    hemiSky: '#e8ffe0',
    hemiGround: '#2a3a1a',
    hemi: 0.9,
    sun: '#fff6d8',
    sunI: 1.7,
    accent: '#ff6fcf',
    mood: 'leaves',
    space: false,
    bloom: 0.18,
    outdoor: { ground: 'jungle', ground2: '#3a6a20', rock: '#5c6650', rockDark: '#3a4232', below: '#1f4a18', sunDisc: '#fff8e0', clouds: '#e8f4e8', hills: '#3c6a48', stars: false },
  },
  volcano: {
    skyTop: '#1c0a10',
    skyBottom: '#7a2c18',
    fog: '#3e1a12',
    fogNear: 42,
    fogFar: 150,
    floor: '#3a3236',
    floorLine: '#241c1e',
    floorSide: '#241c1e',
    ice: '#a0a8b8',
    wall: '#2e2628',
    wallTrim: '#ff3a4c',
    edge: '#ff8a4a',
    hazard: '#ff6a12',
    hazardDeep: '#5a1004',
    hemiSky: '#ffb08a',
    hemiGround: '#2a0a08',
    hemi: 0.7,
    sun: '#ffb080',
    sunI: 1.55,
    accent: '#ff3a4c',
    mood: 'ash',
    space: false,
    bloom: 0.24,
    outdoor: { ground: 'basalt', ground2: '#4a3a38', rock: '#3a2e2e', rockDark: '#1e1616', below: '#ff5a10', belowGlow: true, sunDisc: '#ff9060', clouds: '#4a2a24', hills: '#2a1414', stars: false },
  },
  /* Chapter 3: the Argo's voyage. A flight level has no deck to build; the vehicle stages its own sky. */
  rocks: {
    skyTop: '#05061a',
    skyBottom: '#1a1240',
    fog: '#120c30',
    fogNear: 90,
    fogFar: 300,
    floor: '#6a6478',
    floorLine: '#3a3448',
    floorSide: '#2a2438',
    ice: '#cfd6ff',
    wall: '#4a4258',
    wallTrim: '#ffd166',
    edge: '#ffd166',
    hazard: '#ffb84a',
    hazardDeep: '#4a2a08',
    hemiSky: '#d8d0ff',
    hemiGround: '#2a1a30',
    hemi: 0.6,
    sun: '#fff0d8',
    sunI: 1.5,
    accent: '#ffd166',
    mood: 'motes',
    space: true,
    bloom: 0.32,
  },
  /* The Harpy Isles: grassy sky-islands on stone stems, high above a sea of clouds. */
  harpies: {
    skyTop: '#2f7ad0',
    skyBottom: '#ffe6c8',
    fog: '#e8eef6',
    fogNear: 64,
    fogFar: 215,
    floor: '#6aac44',
    floorLine: '#468a2c',
    floorSide: '#8a6a4c',
    ice: '#c8ecff',
    wall: '#a8988a',
    wallTrim: '#2fb7a3',
    edge: '#d8f0a0',
    hazard: '#7fd8ff',
    hazardDeep: '#2a6a9a',
    hemiSky: '#f0f6ff',
    hemiGround: '#6a7a5a',
    hemi: 1.05,
    sun: '#fff0d8',
    sunI: 2.1,
    accent: '#2fb7a3',
    mood: 'petals',
    space: false,
    bloom: 0.14,
    outdoor: { ground: 'grass', ground2: '#9ccc5a', rock: '#a8988a', rockDark: '#6e6052', below: '#f4f6fb', sunDisc: '#fff4dc', clouds: '#ffffff', hills: '#c8d8ee', stars: false, cloudSea: true },
  },
  /* Scylla's Reef: pale coral sand and dark reef rock in a bright turquoise sea, under a tropical sun. */
  reef: {
    skyTop: '#2a8ad8',
    skyBottom: '#d6f2ff',
    fog: '#c8ecf8',
    fogNear: 62,
    fogFar: 210,
    floor: '#f0d8bc',
    floorLine: '#d4b28c',
    floorSide: '#b88a68',
    ice: '#c8f0ff',
    wall: '#8a7c74',
    wallTrim: '#ff7a8a',
    edge: '#fff2dc',
    hazard: '#3fc8e0',
    hazardDeep: '#0a4a6a',
    hemiSky: '#eaf8ff',
    hemiGround: '#5e8a8a',
    hemi: 1.05,
    sun: '#fff4dc',
    sunI: 2.2,
    accent: '#3fe0d0',
    mood: 'motes',
    space: false,
    bloom: 0.14,
    outdoor: { ground: 'sand', ground2: '#fbe6cf', rock: '#8c7d74', rockDark: '#5a4e48', below: '#0c4f72', sunDisc: '#fffbe8', clouds: '#ffffff', hills: '#7aa6bc', stars: false, sea: true },
  },
  /* Aeëtes's Mine: an open-pit gold mine on a dusty moon, under a black sky full of stars, with molten ore glowing at the bottom of the pit. */
  mine: {
    skyTop: '#070614',
    skyBottom: '#3a2a3e',
    fog: '#2e2230',
    fogNear: 48,
    fogFar: 165,
    floor: '#7a6a5a',
    floorLine: '#4a3e34',
    floorSide: '#3a3028',
    ice: '#c8d0e8',
    wall: '#5e4e42',
    wallTrim: '#ffc23a',
    edge: '#ffc23a',
    hazard: '#ffaa22',
    hazardDeep: '#5a2a04',
    hemiSky: '#ffd8b0',
    hemiGround: '#2a1a14',
    hemi: 0.72,
    sun: '#fff0d8',
    sunI: 1.7,
    accent: '#ffc23a',
    mood: 'dust',
    space: false,
    bloom: 0.26,
    outdoor: { ground: 'rock', ground2: '#9a8466', rock: '#6e5c4c', rockDark: '#3e322a', below: '#ff9a20', belowGlow: true, sunDisc: '#fff4e0', clouds: null, hills: '#4a3a48', stars: true },
  },
  /* The Sirens' Sea: under the ocean of a water moon, sunlit blue-green above and deep blue below. The sub stages its own sea. */
  sirens: {
    skyTop: '#3ab8d8',
    skyBottom: '#031a30',
    fog: '#0b4f6e',
    fogNear: 12,
    fogFar: 105,
    floor: '#c8b88a',
    floorLine: '#8a7a5a',
    floorSide: '#5a4e3a',
    ice: '#c8f0ff',
    wall: '#3a5a6a',
    wallTrim: '#4ae0d8',
    edge: '#4ae0d8',
    hazard: '#ff6fb0',
    hazardDeep: '#3a0a2a',
    hemiSky: '#a8f0ff',
    hemiGround: '#0a2a3a',
    hemi: 0.85,
    sun: '#d8f6ff',
    sunI: 1.35,
    accent: '#4ae0d8',
    mood: 'motes',
    space: false,
    bloom: 0.3,
  },
  /*
   * Talos's Forge: a bronze volcanic island in a teal sea, late afternoon. Black basalt with bronze-green
   * patina, copper-coloured cliffs, glowing lava channels, a hazy amber sky and the sea far below.
   */
  forge: {
    skyTop: '#2f6f9a',
    skyBottom: '#ffc88a',
    fog: '#d8a27a',
    fogNear: 50,
    fogFar: 170,
    floor: '#4a3a34',
    floorLine: '#2e2420',
    floorSide: '#2e2420',
    ice: '#c8e8f0',
    wall: '#8a5a3a',
    wallTrim: '#e0a040',
    edge: '#ffb050',
    hazard: '#ff7a1a',
    hazardDeep: '#6a1a04',
    hemiSky: '#ffe0c0',
    hemiGround: '#3a2018',
    hemi: 0.85,
    sun: '#ffd8a8',
    sunI: 1.9,
    accent: '#e0a040',
    mood: 'embers',
    space: false,
    bloom: 0.24,
    outdoor: { ground: 'basalt', ground2: '#4a5a44', rock: '#9a6440', rockDark: '#5a3424', below: '#1f6a80', sunDisc: '#fff0d0', clouds: '#ffe4c8', hills: '#3a2a2e', stars: false },
  },
  /*
   * Medusa's Labyrinth: a vast cavern under Colchis, walls of green stone carved by the Gardeners,
   * glowing crystals in the dark roof like stars, and MEDUSA's green light everywhere.
   */
  labyrinth: {
    skyTop: '#020a08',
    skyBottom: '#0e2a22',
    fog: '#0c2620',
    fogNear: 34,
    fogFar: 120,
    floor: '#5e7a68',
    floorLine: '#3a5244',
    floorSide: '#2e4036',
    ice: '#b8f0d8',
    wall: '#4a6656',
    wallTrim: '#7dff9a',
    edge: '#e8b84a',
    hazard: '#3dff8a',
    hazardDeep: '#06301c',
    hemiSky: '#c8ffe0',
    hemiGround: '#1a2a20',
    hemi: 0.8,
    sun: '#e8fff0',
    sunI: 1.5,
    accent: '#7dff9a',
    mood: 'spores',
    space: false,
    bloom: 0.3,
    outdoor: { ground: 'rock', ground2: '#6a8a5a', rock: '#5a7666', rockDark: '#2e4438', below: '#0a2a1a', sunDisc: '#c8ffd8', clouds: null, hills: '#0e221a', stars: true },
  },
};
